### PR TITLE
31 support netframework

### LINKED ISSUE #31: Hope to support.Net 4.5.2 version above.
I used this library in version. net 4.6.1 and found it unavailable. The AssemblyLoadContext method reported an error, hoping to support. net 4.6.

### PR DESCRIPTION
**Pull request by bloritsch**
Fixes #31 

## Proposed Changes

  - Addressed concern I had before about missing generating the assembly over and over.
  - Incorporate code from @honorduan

### CODE REVIEW

**Comment by honorduan** [comment]
I have tested this, this place should be allowed to be created more than once, otherwise the new object will be empty. Like var test = new Faux < ITest1 > (). The Service; Ver test2 = new Faux < ITest2 > (); Test2 wiil be null.

**Comment by honorduan** [comment]
I have tested this, this place should be allowed to be created more than once, otherwise the new object will be empty. Like var test = new Faux < ITest1 > (). The Service; Ver test2 = new Faux < ITest2 > (); Test2 wiil be null.

**Comment by bloritsch** [comment]
The key is that all interfaces are registered as soon as possible.  That's what the constructor of the object Faux<TService> is doing.  The actual retrieval of the service is intentionally delayed until the first call to faux.Service.

I'm adding a new method to make that easier.

**Comment by honorduan** [comment]
Well, that would be better

**Comment by bloritsch** [comment]
Updated the TypeFactory to be able to handle the case where the assembly was already generated, and force it to be generated again.  Adds a warning to the log since this is a performance impact.

**Pull request merged**
